export const API_URL = process.env.NEXT_PUBLIC_API_URL;

export const API_ENDPOINTS = {
  USER: `${API_URL}/user`,
  USER_CONFIG: `${API_URL}/user-config`,
  COMPANY: `${API_URL}/company`,
  DIVISION: `${API_URL}/division`,
  ROLE: `${API_URL}/role`,
  SKILL: `${API_URL}/skill`,
  SKILL_LEVEL: `${API_URL}/skill-level`,
  SKILL_CATEGORY: `${API_URL}/skill-category`,
  CALENDAR: `${API_URL}/calendar`,
  RESOURCE: `${API_URL}/resource`,
  RESOURCE_POOL: `${API_URL}/resource-pool`,
  PROJECT_GROUP: `${API_URL}/project-group`,
  PROJECT_GROUP_STRUCTURE_HDR: `${API_URL}/project-group-structure-hdr`,
  PROJECT_GROUP_STRUCTURE_DTL: `${API_URL}/project-group-structure-dtl`,
  PROJECT: `${API_URL}/project`,
  TASK: `${API_URL}/task`,
  TASK_TYPE: `${API_URL}/task-type`,
  TASK_LABEL: `${API_URL}/task-label`,
  COMMENT: `${API_URL}/comment`,
  TICKET_SPACE: `${API_URL}/ticket-space`,
  TICKET_QUEUE: `${API_URL}/ticket-queue`,
  TICKET: `${API_URL}/ticket`,
  TICKET_ATTACHMENT: `${API_URL}/ticket-attachment`,
  NOTIFICATION: `${API_URL}/notification`,
  TASK_SPACE: `${API_URL}/task-space`,
  TASK_SPACE_HIERARCHY_LEVEL: `${API_URL}/task-space-hierarchy-level`,
  TASK_MANAGEMENT_TASK: `${API_URL}/task-management/task`,
  TASK_MANAGEMENT_TASK_LABEL: `${API_URL}/task-management/task-label`,
  TASK_MANAGEMENT_TASK_CHECKLIST: `${API_URL}/task-management/task-checklist`,
  ALERT_RULE: `${API_URL}/alert-rule`,
  DASHBOARD: `${API_URL}/dashboard`,
  SYNALYTICS: `${API_URL}/synalytics`,
  NOTES: `${API_URL}/notes`,
  WORK_LOG: `${API_URL}/work-log`,
  EXPORT_EXCEL_TASK: `${API_URL}/export/excel/task`,
  EXPORT_EXCEL_TICKET: `${API_URL}/export/excel/ticket`,
  LINK_TYPE: `${API_URL}/link-management/link-type`,
  WORK_ITEM_LINK: `${API_URL}/link-management/work-item-link`,
  EXPORT_EXCEL: `${API_URL}/export/excel`,
  IMPORT_EXCEL: `${API_URL}/import/excel`,
  PULSE: `${API_URL}/pulse`,
  TICKET_TEMPLATE: `${API_URL}/ticket-templates`,
  CHAT: `${API_URL}/chat`,
};

